### ISSUE TITLE
Determining the structure for errors 

### ISSUE THREAD

**Issue by YourAlly** [GentleHome/trestle-prototype#15]
We need to determine what the structure for returning errors from the php is

so that it can be written and handled on a consistent manner

**Comment by YourAlly** [comment]
do we just return an object like
`
{
    "error": "Error Message!"   
}
`

**Comment by GentleHome** [comment]
Is that an easier implementation? Or just make client side check if it returned object/json. Like
typeof(data) == 'object'.

But your idea seems cleaner though.

**Comment by YourAlly** [comment]
I think it's an easier implementation, so that if object.error returns true we can also check what went wrong

**Comment by YourAlly** [comment]
We can close this, will create an issue for implementing this, probably around before or after the completion of the MVP
