### ISSUE TITLE
Create get all announcements and all course works endpoints

### ISSUE THREAD

**Issue by GentleHome** [GentleHome/trestle-prototype#16]
As of today, we still have to manually put the courseid to get the duedates announcements and such. I want to use the current [code ](https://github.com/GentleHome/trestle-prototype/tree/master/api)to do this.

**Comment by YourAlly** [comment]
Do you mean the implementation of get all due courseworks, get all announcements and stuff?

**Comment by YourAlly** [comment]
I do have a way for it to be implemented for now (a bit heavy on the backend side, but should be cleaner for the frontend)

**Comment by GentleHome** [comment]
As of now the code you provided we have to put the courseid manually and stuff right?

What does your implementation return on backend? JSON?

**Comment by GentleHome** [comment]
in getting announcements it should be course_code not course_id
`https://canvas.instructure.com/api/v1/announcements?context_codes[]=' . $course_code, $headers`

**Comment by GentleHome** [comment]
Getting announcements
`'https://canvas.instructure.com/api/v1/announcements?context_codes[]=course_' . $course_id, $headers`

Previously
'https://canvas.instructure.com/api/v1/announcements?context_codes[]=' . $course_id, $headers
