### ISSUE TITLE
Best way to display announcements

### ISSUE THREAD

**Issue by GentleHome** [GentleHome/trestle-prototype#20]
1. I dont think announcements should be placed inside the calendar.
2. Is it good to just put in on task checklist?
3. Do we need propose a new view to contain it?

If were too lazy to make a new view well, i can just put it in calendar anyway.
**Need your opinions thanks!**

**Comment by YourAlly** [comment]
1. Yeah that's a good point, maybe we create a new page for it?
2. No I don't think that's a good idea either since it's not a task checklist.
3. I'd love a view for it yeah.
