### ISSUE TITLE
Implement Doctrine on our web app

### ISSUE THREAD

**Issue by YourAlly** [GentleHome/trestle-prototype#22]
Whatever happens here, I will be held accountable, I'll apologize in advance

Using Doctrine will help us in being more flexible with which database to use, and have a more solid structure on how we interact with the database objects.

Mainly this will make my life easier (I confess), but it being easier for me means easier for the rest of the group (I don't think they'll touch the db either way).

**Comment by YourAlly** [comment]
I'M RUINING OUR CAPSTONE LET'S GOOOOOOO

**Comment by GentleHome** [comment]
![image](https://user-images.githubusercontent.com/70477284/140645171-f4c10e02-7f59-4578-96f4-d567e1f011a8.png)

**Comment by YourAlly** [comment]
PR up [Link to PR](https://github.com/GentleHome/trestle-prototype/pull/23)

You can close this as soon as it's ok for you

**Comment by YourAlly** [comment]
If we're going sqlite the whole way, I'll regret this decision.

If we're not, I'll still regret this decision (but not that much).
