### ISSUE TITLE
Logdat

### ISSUE THREAD

**Issue by YourAlly** [GentleHome/trestle-prototype#46]

**Comment by GentleHome** [comment]
helikopter

**Comment by GentleHome** [comment]
optimus pride

**Comment by YourAlly** [comment]
Local setup for Logdat is almost finished, although we encountered a problem with missing drivers today.

We might have to switch to a database everyone can use properly @GentleHome

**Comment by YourAlly** [comment]
Logdat's local is now properly set up (also has the recording for reference)
