### ISSUE TITLE
Create POST add_schedule / add_task / add_reminder

### ISSUE THREAD

**Issue by YourAlly** [GentleHome/trestle-prototype#8]
I need to create an API endpoint that will serve as the way to to create a new reminder

**Comment by YourAlly** [comment]
Ah for this ticket it's only the creation of the API endpoints, might try to work on applying it on the frontend

**Comment by YourAlly** [comment]
https://github.com/GentleHome/trestle-prototype/issues/22

**Comment by YourAlly** [comment]
The endpoints for this issue will be at V1 I guess

**Comment by YourAlly** [comment]
For now I'll create them at separate endpoints, then just combine them if it's unnecessary

**Comment by YourAlly** [comment]
I just realized this needs login and register first

**Comment by YourAlly** [comment]
Finally working on it: https://github.com/GentleHome/trestle-prototype/tree/feature/reminders-api-endpoints

**Comment by YourAlly** [comment]
I WILL DO MY BEST TO GET THIS DONE BEFORE SATURDAY

**Comment by miraroy-manulife** [comment]
Actually most of the implementation for these endpoints is already done on the cli-utils folder, it's just a matter of copy-pasting and changing some stuff

**Comment by YourAlly** [comment]
No, get out

**Comment by miraroy-manulife** [comment]
bro...

**Comment by YourAlly** [comment]
Code is already there, will be tested later or tomorrow to check things out before merging into our code

**Comment by YourAlly** [comment]
Tested and done
